angular.module("app")
.filter("skypeUri", ()->
  suffix = if Detectizr.os.name is "ios" then "chat" else "userinfo"
  (input)-> "skype:#{input}?#{suffix}"
).filter("prefectureParentheses", ()->
  parsePrefectureName = (code)->
    switch code
      when "JP-01" then "北海道"
      when "JP-02" then "青森県"
      when "JP-03" then "岩手県"
      when "JP-04" then "宮城県"
      when "JP-05" then "秋田県"
      when "JP-06" then "山形県"
      when "JP-07" then "福島県"
      when "JP-08" then "茨城県"
      when "JP-09" then "栃木県"
      when "JP-10" then "群馬県"
      when "JP-11" then "埼玉県"
      when "JP-12" then "千葉県"
      when "JP-13" then "東京都"
      when "JP-14" then "神奈川県"
      when "JP-15" then "新潟県"
      when "JP-16" then "富山県"
      when "JP-17" then "石川県"
      when "JP-18" then "福井県"
      when "JP-19" then "山梨県"
      when "JP-20" then "長野県"
      when "JP-21" then "岐阜県"
      when "JP-22" then "静岡県"
      when "JP-23" then "愛知県"
      when "JP-24" then "三重県"
      when "JP-25" then "滋賀県"
      when "JP-26" then "京都府"
      when "JP-27" then "大阪府"
      when "JP-28" then "兵庫県"
      when "JP-29" then "奈良県"
      when "JP-30" then "和歌山県"
      when "JP-31" then "鳥取県"
      when "JP-32" then "島根県"
      when "JP-33" then "岡山県"
      when "JP-34" then "広島県"
      when "JP-35" then "山口県"
      when "JP-36" then "徳島県"
      when "JP-37" then "香川県"
      when "JP-38" then "愛媛県"
      when "JP-39" then "高知県"
      when "JP-40" then "福岡県"
      when "JP-41" then "佐賀県"
      when "JP-42" then "長崎県"
      when "JP-43" then "熊本県"
      when "JP-44" then "大分県"
      when "JP-45" then "宮崎県"
      when "JP-46" then "鹿児島県"
      when "JP-47" then "沖縄県"
  (input)->
    prefecture = parsePrefectureName(input)
    if prefecture? then "（" + prefecture + "）" else ""
)
